'use client';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VDEy8FeZY75
 */
import { Button } from '@/components/ui/button';
import { CardContent, Card } from '@/components/ui/card';
import { ArrowUpRight, X } from 'lucide-react';
import { useState } from 'react';
import Link from 'next/link';

export function EquipeCard() {
	const [show, setShow] = useState(true);
	function hideCard() {
		setShow(false);
	}

	if (!show) return null;
	return (
		<Card
			className={`absolute left-0 top-[50vh] z-10 mx-auto w-full max-w-lg scale-[80%] space-y-4 overflow-hidden rounded-xl bg-white shadow-2xl dark:bg-gray-800 lg:fixed lg:top-[35vh] lg:scale-[65%] 2xl:left-[00px] 2xl:scale-[75%] 3xl:right-[8vw] 3xl:top-[15vh] 3xl:scale-[90%] 3xl:space-y-0`}>
			<div className='relative flex items-center justify-between bg-gradient-to-r from-blue-300 to-secondaryOne px-6 py-4'>
				<div className='flex items-center space-x-3'>
					<h1 className='text-xl font-bold text-black'>
						Demandez un devis
					</h1>
					<svg
						className=' h-8 w-8'
						fill='none'
						height='16'
						stroke='currentColor'
						strokeLinecap='round'
						strokeLinejoin='round'
						strokeWidth='2'
						viewBox='0 0 24 24'
						width='16'
						xmlns='http://www.w3.org/2000/svg'>
						<path d='M4 10h12' />
						<path d='M4 14h9' />
						<path d='M19 6a7.7 7.7 0 0 0-5.2-2A7.9 7.9 0 0 0 6 12c0 4.4 3.5 8 7.8 8 2 0 3.8-.8 5.2-2' />
					</svg>
				</div>
				<X
					className='cursor-pointer text-blackOne hover:scale-105'
					onClick={hideCard}
				/>
			</div>
			<CardContent className='p-4'>
				<p className='text-center text-sm leading-relaxed text-gray-700 dark:text-gray-300'>
					Nous vous proposons des devis sur mesure adapté à votre
					situations et pouvons intervenir en co-animation.
				</p>
				<Link href='/contact'>
					<Button
						size={'sm'}
						className='m-auto mt-6 flex justify-center gap-2 bg-primaryOne lg:w-[45%] 3xl:mt-4'>
						{' '}
						<span className='text-sm'>En savoir plus</span>{' '}
						<ArrowUpRight />
					</Button>
				</Link>
			</CardContent>
		</Card>
	);
}
