'use client';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VDEy8FeZY75
 */
import { Button } from '@/components/ui/button';
import { CardContent, Card } from '@/components/ui/card';
import { ArrowUpRight, X } from 'lucide-react';
import { useState } from 'react';
import Link from 'next/link';

export function StudentCard() {
	const [show, setShow] = useState(true);
	function hideCard() {
		setShow(false);
	}

	if (!show) return null;
	return (
		<Card
			className={`fixed right-[5vw] top-[16vh] z-10 mx-auto w-full max-w-lg scale-[75%] space-y-4 overflow-hidden rounded-xl bg-white shadow-2xl dark:bg-gray-800 2xl:scale-[85%] 3xl:right-[8vw] 3xl:top-[15vh] 3xl:scale-[90%] 3xl:space-y-0`}>
			<div className='relative flex items-center justify-between bg-gradient-to-r from-blue-300 to-secondaryOne px-6 py-4'>
				<div className='flex items-center space-x-3'>
					<h1 className='text-xl font-bold text-white'>Tarifs Réduits</h1>
					<svg
						className=' h-8 w-8 text-white'
						fill='none'
						height='24'
						stroke='currentColor'
						strokeLinecap='round'
						strokeLinejoin='round'
						strokeWidth='2'
						viewBox='0 0 24 24'
						width='24'
						xmlns='http://www.w3.org/2000/svg'>
						<path d='M22 10v6M2 10l10-5 10 5-10 5z' />
						<path d='M6 12v5c3 3 9 3 12 0v-5' />
					</svg>
					<svg
						className=' h-8 w-10 text-white'
						fill='none'
						height='24'
						stroke='currentColor'
						strokeLinecap='round'
						strokeLinejoin='round'
						strokeWidth='2'
						viewBox='0 0 24 24'
						width='24'
						xmlns='http://www.w3.org/2000/svg'>
						<path d='M12 2H2v10l9.29 9.29c.94.94 2.48.94 3.42 0l6.58-6.58c.94-.94.94-2.48 0-3.42L12 2Z' />
						<path d='M7 7h.01' />
					</svg>
				</div>
				<X
					className='cursor-pointer text-blackOne hover:scale-105'
					onClick={hideCard}
				/>
			</div>
			<CardContent className='p-4'>
				<p className='text-center text-sm leading-relaxed text-gray-700 dark:text-gray-300'>
					Nous appliquons des tarifs spéciaux pour les étudiants, les
					demandeurs d'emploi et les publics en difficulté financière.
				</p>
				<Link href='/contact'>
					<Button
						size={'sm'}
						className='m-auto mt-6 flex w-[45%] justify-center gap-2 bg-primaryOne 3xl:mt-4'>
						{' '}
						<span className='text-sm'>En savoir plus</span>{' '}
						<ArrowUpRight />
					</Button>
				</Link>
			</CardContent>
		</Card>
	);
}
